version: "3.9"
services:
  mysql:
    image: mysql:5.7.22
    platform: 'linux/amd64'
    container_name: desafio-mysql57
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    networks:
      - network-desafio

networks:
  network-desafio:
    driver: bridge